//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKDSurveillance_RD
{


    public partial class Default
    {

        /// <summary>
        /// SurveyModal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CKDSurveillance_RD.UserControls.RDVersions.SurveyModal SurveyModal;

        /// <summary>
        /// MainImage1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CKDSurveillance_RD.UserControls.FPWidgets.MainImage MainImage1;

        /// <summary>
        /// AboutKDS1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CKDSurveillance_RD.UserControls.FPWidgets.AboutKDS AboutKDS1;

        /// <summary>
        /// AYA1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CKDSurveillance_RD.UserControls.FPWidgets.AYA AYA1;

        /// <summary>
        /// RiskCalculator1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CKDSurveillance_RD.UserControls.FPWidgets.RiskCalculator RiskCalculator1;

        /// <summary>
        /// Prevalence1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CKDSurveillance_RD.UserControls.FPWidgets.Prevalence Prevalence1;

        /// <summary>
        /// RiskFactorsForKD1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CKDSurveillance_RD.UserControls.FPWidgets.RiskFactorsForKD RiskFactorsForKD1;

        /// <summary>
        /// DataBiteHighlights control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CKDSurveillance_RD.UserControls.FPWidgets.DataBiteHighlights DataBiteHighlights;

        /// <summary>
        /// OutcomesQofCare1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CKDSurveillance_RD.UserControls.FPWidgets.OutcomesQofCare OutcomesQofCare1;

        /// <summary>
        /// OutcomesQofCare2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CKDSurveillance_RD.UserControls.FPWidgets.OutcomesQofCare OutcomesQofCare2;

        /// <summary>
        /// GeneralInformation1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CKDSurveillance_RD.UserControls.FPWidgets.GeneralInformation GeneralInformation1;
    }
}
